version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0
  aws-ecr: circleci/aws-ecr@9.0
  docker: circleci/docker@2.4.0


  # build:
  #   description: "Setup Spring boot application and run tests"
  #   docker:
  #     - image: cimg/openjdk:19.0.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build
  #         command: mvn -B -DskipTests clean package
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .

workflows:
  simple_workflow:
    jobs:
      - aws-ecr/build_and_push_image:
          auth:
            - aws-cli/setup:
                role_arn: arn:aws:iam::966576247265:role/oidc-ecr
          # account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          # aws-access-key-id: ${AWS_ACCESS_KEY_ID}
          # aws-secret-access-key: ${AWS_SECRET_ACCESS_KEY}
          # context: myContext
          # create-repo: false
          # dockerfile: Dockerfile
          # profile-name: myProfileName
          # repo: Devops
          # tag: latest
          # #account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          # repo: "${AWS_RESOURCE_NAME_PREFIX}"
          # #region: ${AWS_DEFAULT_REGION}
          # tag: "latest"