version: 2.1

orbs:
  #aws-ecr: circleci/aws-ecr@9.0.1
  docker: circleci/docker@2.4.0

jobs:
  - build
      docker:
        - image: cimg/node:16.10
      # aws-ecr/build_and_push_image:
      #   account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
      #   repo: "${AWS_RESOURCE_NAME_PREFIX}"
      #   region: ${AWS_DEFAULT_REGION}
      #   tag: "latest"
  # build:
  #   description: "Setup Spring boot application and run tests"
  #   docker:
  #     - image: cimg/openjdk:19.0.1
  #   steps:
  #     - checkout
  #     - run:
  #         name: Build
  #         command: mvn -B -DskipTests clean package
  #     - persist_to_workspace:
  #         root: .
  #         paths:
  #           - .

workflows:
  simple_workflow:
    jobs:
      - build